"""Publish the canonical x0me/fplbench dataset card with a live record.

Reads the versioned dataset-card template, replaces its bounded live block
from RESULTS.md (published `e_points_final` MAE) and the official FPL API
(team performance), then uploads the complete card. The Hub is a publication
target, not the source of truth for the surrounding documentation.

The HF token is read from the HF_TOKEN environment variable ONLY and is never
printed or logged.

Usage:
  HF_TOKEN=... python scripts/publish_hf_card.py
  python scripts/publish_hf_card.py --dry-run   # build + print, no upload
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
SCRIPTS = Path(__file__).resolve().parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

from track_team import (  # noqa: E402
    ENTRY_ID,
    TEAM_NAME,
    TEAM_URL,
    build_team_rows,
)

from fplbench.score import split_results_md  # noqa: E402

REPO_ID = "x0me/fplbench"
GITHUB_URL = "https://github.com/PascalAI2024/fplbench"
SCOREBOARD_HEADING = "## Live record — 2026/27"
DEFAULT_RESULTS = ROOT / "RESULTS.md"
DEFAULT_TEMPLATE = ROOT / "docs" / "huggingface" / "DATASET_CARD.md"
LIVE_START = "<!-- LIVE_SCOREBOARD:START -->"
LIVE_END = "<!-- LIVE_SCOREBOARD:END -->"

def _fmt(v: float) -> str:
    import math

    return "" if v is None or (isinstance(v, float) and math.isnan(v)) else f"{v:.4f}"


def model_summary_table_md(rows: dict[int, dict]) -> str:
    out = [
        "| GW | scored rows | fplbench MAE | FPL `ep_next` MAE | lower by |",
        "| ---: | ---: | ---: | ---: | ---: |",
    ]
    for gw in sorted(rows):
        m = rows[gw]
        model = m["mae_model"]
        baseline = m["mae_ep_next"]
        edge = baseline - model
        out.append(
            f"| {gw} | {m['n_common']} | {_fmt(model)} | {_fmt(baseline)} | "
            f"{edge:+.4f} |"
        )
    return "\n".join(out)


def team_summary_table_md(rows: list[dict]) -> str:
    out = [
        "| GW | points | average | vs average | overall rank |",
        "| ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in sorted(rows, key=lambda item: item["gw"]):
        status = row.get("status") or ("live" if row["live"] else "final")
        gw = f"{row['gw']} ({status})" if status != "final" else str(row["gw"])
        vs = row["vs_avg"]
        vs_cell = "—" if vs is None else (f"+{vs}" if vs > 0 else str(vs))
        rank = row["overall_rank"]
        out.append(
            f"| {gw} | {'—' if row['points'] is None else row['points']} | "
            f"{'—' if row['average'] is None else row['average']} | {vs_cell} | "
            f"{'—' if rank is None else format(rank, ',')} |"
        )
    return "\n".join(out)


def build_scoreboard(results_path: Path) -> str:
    _, mae_rows, _ = split_results_md(
        results_path.read_text(encoding="utf-8") if results_path.exists() else ""
    )
    team_rows = build_team_rows()

    parts = [SCOREBOARD_HEADING, ""]
    parts.append(
        "Generated by the [fplbench public workflow]"
        f"({GITHUB_URL}/blob/main/.github/workflows/publish-public-surfaces.yml) "
        "from the frozen forecast and official FPL actuals. Lower MAE is better."
    )
    parts += [
        "",
        "### Frozen model score — `e_points_final` vs FPL `ep_next`",
        "",
    ]
    if mae_rows:
        parts.append(model_summary_table_md(mae_rows))
    else:
        parts.append(
            "No finished gameweek has been scored yet. The workflow publishes "
            "the first row only after FPL marks it finished and data-checked."
        )
    parts += ["", f"### Live team — {TEAM_NAME}", ""]
    if team_rows:
        latest = max(team_rows, key=lambda item: item["gw"])
        parts.append(
            f"Current captain: **{latest['captain']}** · official entry "
            f"**{ENTRY_ID}**"
        )
        parts += ["", team_summary_table_md(team_rows)]
    else:
        parts.append("No gameweek data yet.")
    parts += [
        "",
        f"[Open the visual board](https://huggingface.co/spaces/x0me/fplbench-board) · "
        f"[inspect the committed forecast]({GITHUB_URL}/tree/main/outputs/predictions) · "
        f"[view the official team]({TEAM_URL})",
        "",
        f"_Last refreshed: {dt.datetime.now(dt.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_",
    ]
    return "\n".join(parts)


def replace_live_block(template: str, section: str) -> str:
    """Replace the single bounded live block or fail closed."""
    if template.count(LIVE_START) != 1 or template.count(LIVE_END) != 1:
        raise ValueError("dataset card template must contain one live block")
    start = template.index(LIVE_START)
    end = template.index(LIVE_END, start) + len(LIVE_END)
    return template[:start] + LIVE_START + "\n" + section + "\n" + LIVE_END + template[end:]


def build_card(results_path: Path, template_path: Path = DEFAULT_TEMPLATE) -> str:
    template = template_path.read_text(encoding="utf-8")
    card = replace_live_block(template, build_scoreboard(results_path))
    if not card.endswith("\n"):
        card += "\n"
    return card


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(description="Publish the living HF dataset card")
    p.add_argument("--results", type=Path, default=DEFAULT_RESULTS)
    p.add_argument("--template", type=Path, default=DEFAULT_TEMPLATE)
    p.add_argument("--card", type=Path, help="publish a previously verified card")
    p.add_argument("--output", type=Path, help="write the generated card to this path")
    p.add_argument("--dry-run", action="store_true", help="build + print, no upload")
    args = p.parse_args(argv)

    card = (
        args.card.read_text(encoding="utf-8")
        if args.card is not None
        else build_card(args.results, args.template)
    )
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(card, encoding="utf-8")
    if args.dry_run:
        print(f"dry run: {len(card)} chars, not uploaded")
        if args.output is not None:
            print(f"wrote {args.output}")
        return

    token = os.environ.get("HF_TOKEN")
    if not token:
        raise SystemExit("HF_TOKEN environment variable is required")

    from huggingface_hub import CommitOperationAdd, HfApi, hf_hub_download

    api = HfApi(token=token)
    parent = api.repo_info(REPO_ID, repo_type="dataset").sha
    content = card.encode("utf-8")
    commit = api.create_commit(
        repo_id=REPO_ID,
        repo_type="dataset",
        operations=[CommitOperationAdd(path_in_repo="README.md", path_or_fileobj=content)],
        commit_message="scoreboard: refresh live model + team tables",
        commit_description=f"Atomic card refresh against parent {parent}.",
        parent_commit=parent,
    )
    readback = Path(
        hf_hub_download(
            repo_id=REPO_ID,
            filename="README.md",
            repo_type="dataset",
            revision=commit.oid,
            token=token,
        )
    ).read_bytes()
    if hashlib.sha256(readback).digest() != hashlib.sha256(content).digest():
        raise RuntimeError("immutable dataset-card readback mismatch")
    print(f"uploaded and verified dataset card ({len(card)} chars) -> {commit.commit_url}")


if __name__ == "__main__":
    main()
