"""Upload the generated board to the HF Space x0me/fplbench-board.

Uploads outputs/board/index.html (always) and outputs/board/README.md (only
when it differs from the Space's current README, to avoid noise commits).
Both files are committed atomically against the observed parent revision.

The HF token is read from the HF_TOKEN environment variable ONLY and is never
printed or logged.

Usage:
  python scripts/build_board.py && HF_TOKEN=... python scripts/publish_space.py
  python scripts/publish_space.py --dry-run   # report what would upload
"""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parents[1]
SPACE_ID = "x0me/fplbench-board"
SPACE_README_RAW = f"https://huggingface.co/spaces/{SPACE_ID}/raw/main/README.md"
HEADERS = {"User-Agent": "fplbench/0.1 (research; leakage-safe FPL panel)"}
DEFAULT_DIR = ROOT / "outputs" / "board"


def readme_changed(local: Path) -> bool:
    """True when the local README differs from the Space's current one."""
    try:
        r = requests.get(SPACE_README_RAW, headers=HEADERS, timeout=60)
        r.raise_for_status()
        current = r.text
    except requests.RequestException:
        return True  # can't compare — upload to be safe

    def norm(s: str) -> str:
        return s.replace("\r\n", "\n").strip()

    return norm(current) != norm(local.read_text(encoding="utf-8"))


def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(description=f"Publish the board to {SPACE_ID}")
    p.add_argument("--dir", type=Path, default=DEFAULT_DIR, help="board output dir")
    p.add_argument("--dry-run", action="store_true", help="report, don't upload")
    args = p.parse_args(argv)

    index = args.dir / "index.html"
    readme = args.dir / "README.md"
    if not index.exists():
        raise SystemExit(f"{index} not found — run scripts/build_board.py first")

    uploads = [(index, "index.html")]
    if readme.exists() and readme_changed(readme):
        uploads.append((readme, "README.md"))

    if args.dry_run:
        for path, dest in uploads:
            print(f"would upload {path} -> {SPACE_ID}/{dest}")
        return

    token = os.environ.get("HF_TOKEN")
    if not token:
        raise SystemExit("HF_TOKEN environment variable is required")

    from huggingface_hub import CommitOperationAdd, HfApi, hf_hub_download

    api = HfApi(token=token)
    parent = api.repo_info(repo_id=SPACE_ID, repo_type="space").sha
    operations = [
        CommitOperationAdd(path_in_repo=dest, path_or_fileobj=path)
        for path, dest in uploads
    ]
    commit = api.create_commit(
        repo_id=SPACE_ID,
        repo_type="space",
        operations=operations,
        commit_message="board: publish responsive live surface",
        commit_description=(
            "Atomic refresh generated by PascalAI2024/fplbench. "
            "Source data: frozen forecasts plus official FPL public data."
        ),
        parent_commit=parent,
    )
    names = ", ".join(dest for _, dest in uploads)
    for path, dest in uploads:
        readback = Path(
            hf_hub_download(
                repo_id=SPACE_ID,
                filename=dest,
                repo_type="space",
                revision=commit.oid,
                token=token,
            )
        ).read_bytes()
        expected = path.read_bytes()
        if hashlib.sha256(readback).digest() != hashlib.sha256(expected).digest():
            raise RuntimeError(f"immutable Space readback mismatch for {dest}")
    print(f"uploaded and verified {names} -> {commit.commit_url}")


if __name__ == "__main__":
    main()
